# -*- coding: utf-8 -*-
"""Kalyani_BLS_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Zom4f-S98Eg4z9K5jr5kzPrOuiCkxm3
"""

from bs4 import BeautifulSoup
import requests,re
import pandas as pd
import json
import prettytable

url="https://data.bls.gov/cgi-bin/surveymost?bls"
req=requests.get(url)
content=BeautifulSoup(req.content,'html.parser')
data=content.find_all("dd")
# get all BLS Popular Series id
id_list=[]
match = content.find_all('input',type="checkbox")
for tag in match:
    tag_value =  tag.get('value')
    #print(tag_value)
    id_list.append(tag_value)
print(id_list)

#get all BLS Popular Series in csv format
headers = {'Content-type': 'application/json'}
data = json.dumps({"seriesid": id_list,"startyear":"1948", "endyear":"2022"})
p = requests.post('https://api.bls.gov/publicAPI/v1/timeseries/data/', data=data, headers=headers)
json_data = json.loads(p.text)
for series in json_data['Results']['series']:
    x=prettytable.PrettyTable(["series id","year","period","value","footnotes"])
    seriesId = series['seriesID']
    for item in series['data']:
        year = item['year']
        period = item['period']
        value = item['value']
        footnotes=""
        for footnote in item['footnotes']:
            if footnote:
                footnotes = footnotes + footnote['text'] + ','
    
        if 'M01' <= period <= 'M12':
            x.add_row([seriesId,year,period,value,footnotes[0:-1]])
    output = open(seriesId + '.csv','w') # save data in csv format
    output.write (x.get_string())
    output.close()